### ISSUE TITLE
BpyBuild not installing to folders when addon was not previously installed

### ISSUE THREAD

**Issue by TheDuckCow** [Moo-Ack-Productions/bpy-build#17] opened 2024-06-01 15:46 UTC
Per separate message I noticed blender 4.0+ not getting installed locally. Curious if you have an idea on the issue source here, or if perhaps I have something local messed up

<img width="903" alt="Screen Shot 2024-06-01 at 8 43 25 AM" src="https://github.com/Moo-Ack-Productions/bpy-build/assets/2958461/929480dc-9959-450c-8fa1-8bac4bc5f44c">

**Comment by StandingPadAnimations** [comment] 2024-06-01 16:01
Does the `4.0` folder contain `scripts/addons`? I'm not able to reproduce this on ny end

**Comment by TheDuckCow** [comment] 2024-06-01 16:33
Yup, though let me try in a minute if it changes on manually installing MCprep

<img width="603" alt="Screen Shot 2024-06-01 at 9 33 04 AM" src="https://github.com/Moo-Ack-Productions/bpy-build/assets/2958461/bd9ae312-b623-48fb-a088-086dbeb1a4d2">

**Comment by TheDuckCow** [comment] 2024-06-01 16:38
Yup, that did the trick - with MCprep there, it now installs via bab. So maybe it's an extra directory that needs creation?

**Comment by StandingPadAnimations** [comment] 2024-06-01 16:54
I've found the problem area in question
https://github.com/Moo-Ack-Productions/bpy-build/blob/a0741ec2c2e59e80dfd90f56cfa2bc2ec4abdb02/bpy_addon_build/build_context/install.py#L47

This will be fixed in 0.4.1

**Comment by StandingPadAnimations** [comment] 2024-06-03 00:35
Resolved in [`0dbb26d` (#16)](https://github.com/Moo-Ack-Productions/bpy-build/pull/16/commits/0dbb26d4d0aa7c097975bf24e445fa852d3f3247)

**Closed by StandingPadAnimations** 2024-06-03 00:35 UTC
Labels: bug
